os:
    - linux
    - osx

language: c

sudo: false

before_install:
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then (brew update && brew install glib openssl libgcrypt sqlite3 libpcap pcre || echo -e "\e[1;31m Skipping Homebrew... \e[0m"); fi

addons:
  apt:
    packages:
    - libnl-3-dev
    - libgcrypt11-dev
    - zlib1g-dev
    - libsqlite3-dev
    - libpcap-dev
    - libssl-dev
    - libnl-genl-3-dev
    - libpcre3-dev
    - libglib2.0-0
    - libjson-glib-dev
    - libglib2.0-dev
    - libglib2.0-bin

compiler:
  - gcc
  - clang

script:
    - ./build/travis-format.sh GCrypt "Building with GCrypt..." ./build/gcrypt.sh
    - ./build/travis-format.sh OpenSSL "Building with OpenSSL..." ./build/openssl.sh
    - ./build/travis-format.sh Dist "Creating a dist tarball and then building from it..." ./build/dist_check.sh
