os:
    - linux
    - osx

language: c

sudo: false

before_install:
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then (brew update && brew install libgcrypt sqlite3); fi

addons:
  apt:
    packages:
    - libnl-3-dev
    - libgcrypt11-dev
    - zlib1g-dev
    - libsqlite3-dev
    - libpcap-dev
    - libssl-dev
    - libnl-genl-3-dev
    - libpcre3-dev

compiler:
  - gcc
  - clang

script:
    - if [ "$TRAVIS_OS_NAME" != "osx" ]; then (make libnl=false && make check libnl=false); fi
    - make clean && make sqlite=true experimental=true && make check sqlite=true experimental=true
    - make clean && make sqlite=true experimental=true gcrypt=true && make check sqlite=true experimental=true gcrypt=true
    - make clean && make pcre=true && make check pcre=true
    - export CFLAGS="-g -W -Wall -O0"
    - if [ "$TRAVIS_OS_NAME" != "osx" ]; then (make clean && make libnl=false && make check libnl=false); fi
    - make clean && make sqlite=true experimental=true && make check sqlite=true experimental=true
    - make clean && make sqlite=true experimental=true gcrypt=true && make check sqlite=true experimental=true gcrypt=true
    - make clean && make pcre=true && make check pcre=true
